composer.json
inc/lazyload_replacer.php
tests/test-lazyload.php

Added only query changes from PR #145 
And tests
@selul

fix: lazyload query urls part of #145

---

inc/compatibilities/master_slider.php

chore: compatibility with master slider

---

inc/admin.php

References ans solves Codeinwp/optimole_js_lib#72

fix: edge15 needs poly version of js library

---

inc/admin.php

fix: blur remaining outside of an image after it gets lazyloaded

---

inc/image.php
tests/test-lazyload.php

chore: added cache token for URLs

---

inc/conflicts/divi.php

chore: changed some logic for divi notice display

---

inc/conflicts/divi.php

divi notice sync dev

---

inc/manager.php
tests/test-lazyload.php

This is a patch fix for #228 
https://secure.helpscout.net/conversation/1131986555/223175?folderId=2353196

fix: closes #228 lazy-load tag for non standard latin

---

inc/admin.php

Tested it and works fine without removing the style, that was not needed.

chore: removed redundant code

---

inc/lazyload_replacer.php
tests/test-lazyload.php

I have added the modified regex here for easier testing in case you want to check it. https://regex101.com/r/ijlQP2/5
Fixes #278.

chore: excluded iframes nested inside noscript from lazyload

---

package-lock.json
package.json
webpack.config.js

Updates eslint to be used with eslint webpack plugin.

chore: uses eslint-webpack-plugin

---

.github/workflows/test-e2e.yml
cypress.json

chore: test cypress

---

inc/lazyload_replacer.php
tests/test-lazyload.php

chore: fix video tag source lazyload

---

inc/resource.php

Fixes #346 . Needs to use https://gist.github.com/GrigoreMihai/ff2b866b4a91cb31e3117549ed199acc .

chore: added filter to remove redundant schema

---

inc/admin.php

https://secure.helpscout.net/conversation/1591734956/287831?folderId=2353196 @selul

chore: preserving selected custom domain on stats refresh

---

inc/admin.php

chore: fix lazyload print issue

---

inc/compatibilities/facetwp.php
inc/traits/normalizer.php

Fixes #394 and updates facetwp filtering as suggested here: https://secure.helpscout.net/conversation/1804814254/312352?folderId=2353196 .

chore: updated facetwp compatibility and fixed crop sizes warning

---

inc/app_replacer.php
package-lock.json
package.json

Fixes https://github.com/Codeinwp/optimole-service/issues/541 .

Normalize content url

---

inc/admin.php

Fixes https://github.com/Codeinwp/optimole-service/issues/542 .

chore: added action to check domain change

---

inc/compatibilities/thrive.php
inc/media_offload.php
inc/traits/normalizer.php

Adds an action after we update post content from media_offload. 
Adds compatibility with thrive to update `tve_updated_post` meta after we update the post.

Compatibility thrive

---

inc/app_replacer.php
inc/compatibilities/woocommerce.php
inc/manager.php
inc/media_offload.php

Fixes https://github.com/Codeinwp/optimole-service/issues/585 .

Various fixes

---

assets/js/optimole_media.js

chore: fixed media modal ovveride

---

inc/lazyload_replacer.php
tests/test-lazyload.php

chore: updated iframe lazyload flags to include the default flags #461

---

.github/dependabot.yml

Dependabot GH Workflow Added  
NO
N/A
Closes https://github.com/Codeinwp/themeisle/issues/1445.

chore: dependabot gh workflow added

---

.github/workflows/test-e2e.yml

Closes https://github.com/Codeinwp/themeisle/issues/1445 .

Disable test-e2e.yml for dependabot PRs

---

inc/compatibilities/spectra.php
inc/manager.php

Add compatibility with Spectra blocks.
Closes #571.
1. Make sure Optimole's serve CSS/JS option is disabled.
2. Make sure File Generation is enabled in Spectra.
3. All the images used in Blocks should be served through Optimole.

Add compatibility for Spectra

---

assets/src/parts/connected/settings/OffloadMedia.js
development.php

Fixes the issue with domains not being removed from cloud library whitelist. 
Closes #588.
1. Connect a website with multiple domains with images.
2. Enable the library and see if images from all sites are being fetched. Confirm this doesn't happen: https://github.com/Codeinwp/optimole-wp/issues/588
3. Whitelist multiple domains and confirm images are only loading from those sites.
4. Remove some of those domains and confirm images are only loading from whitelisted sites.
5. Remove all the domains and confirm images are being loaded from all the domains.

fix: sites not being removed from cloud library whitelist

---

bin/dist.sh

Fixes dev build requiring constants too late.
Closes #592.
1. Install dev build from this PR comment
2. Enable cloud browsing
3. Images should be loaded from the staging CDN url
4. Previously images weren't loading throwing a 404;

fix: dev build

---

readme.txt

1. Updated tags and content.
2. Added UTM links.
3. Added use cases.
4. Added Support, documentation section.
Closes # .
N/A

Updated readme content

---

readme.txt

Updated the readme content with our new features details.
Closes # .
N/A

content update: new release features added

---

.github/workflows/test-e2e.yml
cypress/e2e/test_amp.js
cypress/e2e/test_beaver_builder_background_lazyload.js
cypress/e2e/test_divi_background_lazyload.js
cypress/e2e/test_elementor.js
cypress/e2e/test_elementor_background_lazyload.js
cypress/e2e/test_envira.js
cypress/e2e/test_foo.js
cypress/e2e/test_gif.js
cypress/e2e/test_gutenberg.js
cypress/e2e/test_metaslider_background_lazyload.js
cypress/e2e/test_otter_background_lazyload.js
cypress/e2e/test_ss_pintereset.js
cypress/e2e/test_su.js
cypress/e2e/test_thrive_background_lazyload.js
cypress/e2e/test_woo.js
package-lock.json
package.json

Update cypress and fix tests.
Closes #674.
1. Tests should pass
* ~[ ] Have you written new tests for your changes, as applicable?~

fix: cypress e2e tests [closes #674]

---

assets/src/dashboard/parts/connect/APIForm.js
assets/src/dashboard/parts/connect/index.js
assets/src/dashboard/parts/connected/index.js
inc/admin.php
inc/api.php
inc/rest.php

Add a handshake mechanism on connect and register: 
- it sends one sample image from the site 
- it checks if the image is accessible by Optimole; otherwise defaults on the domain check.

add handshake mechanism

---

inc/compatibilities/elementor_builder.php

Address the issue here https://secure.helpscout.net/conversation/2445827292/396016?viewId=2353201

fix replacement in elementor when the setup is not complete.

---

.github/workflows/test-php.yml
bin/install-wp-tests.sh
composer.json
development.php
phpunit.xml
tests/bootstrap.php

This is a PR to update and fix issues running the optimole PHP test suite locally

Fix local PHP tests

---

inc/api.php

Added a new parameter to the OPML service registration API. 
This PR depends on the following OPML service PR:
https://github.com/Codeinwp/optimole-service/pull/1402
Closes https://github.com/Codeinwp/optimole-service/issues/1295
1. Install the plugin using the reference link.  
2. Activate it, navigate to the registration page, and register with a new user.

feat: add reference source

---

assets/src/dashboard/parts/connect/index.js
inc/admin.php
tailwind.config.js

Improve the account connections page layout as suggested [here](https://github.com/Codeinwp/optimole-service/issues/1335#issuecomment-2687267604).
Closes https://github.com/Codeinwp/optimole-service/issues/1335

feat: improve plugin first screen

---

assets/src/dashboard/parts/connected/settings/General.js
assets/src/dashboard/style.scss
inc/admin.php
inc/manager.php
inc/settings.php

Added badge settings to customize the badge position and icon.
Closes https://github.com/Codeinwp/optimole-service/issues/1338
Optimole > Settings -> General -> Enable Optimole Badge

feat: add badge settings

---

assets/src/dashboard/parts/connected/SPCRecommendation.js
assets/src/dashboard/parts/connected/Sidebar.js
assets/src/dashboard/utils/plugin-install.js
inc/admin.php

- Adds SPC recommendation banner to the dashboard sidebar;
| Initial State | Loading State |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/3870bec5-1d3f-4b02-b20a-a1dcc7667c71) | ![image](https://github.com/user-attachments/assets/3510db0b-711d-452f-b1ec-bb081454aa63) |
| Done State | Error State |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/bffa13a6-8af4-4eb6-81fb-8b9a7bf1d364) | ![image](https://github.com/user-attachments/assets/3502210b-1b33-4de3-9cf3-f0f97cf126c1) |
Closes Codeinwp/optimole-service#1407.
1. The banner should be visible on the sidebar in the dashboard;
2. It should not appear if any of the following conditions are fulfilled:
- It has been dismissed;
- The user already has SPC installed and activated;
- The user …

feat: adds SPC banner

---

assets/src/dashboard/parts/components/DashboardMetricBox.js
assets/src/dashboard/parts/components/ProgressBar.js
assets/src/dashboard/parts/connected/dashboard/index.js
assets/src/widget/App.js
assets/src/widget/components/MetricBoxes.js
assets/src/widget/components/Usage.js
assets/src/widget/components/WidgetFooter.js
assets/src/widget/index.js
assets/src/widget/style.scss
inc/admin.php
inc/dashboard_widget.php
package.json
tailwind.config.js

- Adds dashboard widget with stats;
| Normal state | Over 70% |
|--------|--------|
| Going over limit | Skeleton loading state |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/173813f3-e445-47eb-bbf3-a2daa61af992) | ![image](https://github.com/user-attachments/assets/1829d708-1ac2-44a1-8532-ebfbb7034a1b) |
Closes Codeinwp/optimole-service#627.
1. Install the plugin;
2. The widget should be visible in the dashboard if the connected user has more than 10 visits;

feat: adds dashboard widget

---

inc/dashboard_widget.php

- Fixes issue with checking wrong array keys so the dashboard widget didn't show up
1. Have at least 10 visits;
2. Connect to optimole service;
3. The dashboard widget should show on the client site;

fix: dashboard widget not showing

---

assets/src/dashboard/parts/connected/OptimizationStatus.js
assets/src/dashboard/parts/connected/Sidebar.js
inc/admin.php

Add new sidebar box.
Closes https://github.com/Codeinwp/optimole-service/issues/1347

Add optimizaiton tips in sidebar

---

assets/src/dashboard/parts/components/RadioBoxes.js
assets/src/dashboard/parts/connected/settings/OffloadMedia.js

The user must now confirm their decision to complete the action.
Closes https://github.com/Codeinwp/optimole-service/issues/1511

fix: image storage selection
