inc/manager.php, tests/test-lazyload.php
Should solve an edge case where if it encounters early a `<noscript>` tag it will mark all subsequent resources as `in_header` and exclude them from lazy-load
=> fix: small parse fix for lazyload

inc/settings.php
The filters are being reset once the API key is disconnected.
This should keep the filters after the API key is disconnected.
References #206
=> chore: fix losing filters settings after disconnecting the api key

inc/lazyload_replacer.php, tests/test-lazyload.php
One user reported that iframe lazyload breaks gravity forms https://secure.helpscout.net/conversation/1264680679/242528?folderId=2353196. I tested and he is right, gravity forms where excluded after being adding to the search array and where replaced with empty strings. I fixed it by excluding early.
=> chore: fix exclude iframes before adding to replace

cypress/.eslintrc.json, cypress/.prettierrc.json, cypress/integration/test_amp.js, cypress/integration/test_beaver_builder_background_lazyload.js, cypress/integration/test_divi_background_lazyload.js, cypress/integration/test_elementor.js, cypress/integration/test_elementor_background_lazyload.js, cypress/integration/test_envira.js, cypress/integration/test_foo.js, cypress/integration/test_gif.js, cypress/integration/test_gutenberg.js, cypress/integration/test_metaslider_background_lazyload.js, cypress/integration/test_ss_pintereset.js, cypress/integration/test_su.js, cypress/integration/test_thrive_background_lazyload.js, cypress/integration/test_woo.js
- ESLint was added with Prettier to enforce code style and enables checking before commit.
1. ESLint should run according to the rules inside the Cypress folder
=> style: adds Prettier to run with ESLint

cypress/integration/test_elementor_background_lazyload.js, inc/compatibilities/elementor_builder.php, package.json
Fixes #331 . 
There is only one more way to add background that was not covered by the previous compatiblity (the previous classes are working as before). The css replacement works the same in this version. 
For testing I think I can update the current elementor version on testing.optimole.com and include the new background in the cypress test ?
=> chore: updated elementor background lazyload classes

inc/admin.php, readme.txt
This is just a small fix. There are cases when a theme or a plugin will add it's own no-js classes but does not respect the WordPress way of adding them, hence they might get glued to our class. Eg. `optml_no_jsplugin_no_js` instead of. `optml_no_js plugin_no_js` it does not affect the way our plugin works but it might break the no-js functionality of other plugins.
This should improve compatibility.
=> fix: added extra padding for no js class

inc/compatibilities/woocommerce.php, inc/media_offload.php
Fixes https://github.com/Codeinwp/optimole-service/issues/673 . 
Fixes https://github.com/Codeinwp/optimole-service/issues/674 .
Changes:
Uses `POST_OFFLOADED_FLAG` for queries only if the plugin was installed after the flag was added: https://github.com/Codeinwp/optimole-wp/releases/tag/v3.5.0 .
Updates page meta with the `POST_OFFLOADED_FLAG` when an images is uploaded directly into the page. 
Removes redundant(wrong) `POST_OFFLOADED_FLAG` removal on page update.
=> chore: fixed media offload page flag issues

inc/lazyload_replacer.php, tests/test-lazyload.php
Fixes #475 . 
Adds `-src` as a flag for iframe lazyload. 
For testing this we can add any attribute containing `-src` to an iframe and the iframe should be skipped from the lazyload. eg: `data-cli-src` .
=> chore: updated iframe lazyload flags

.github/workflows/build-dev-artifacts.yml
Build workflow was failing on Dependabot PR's. That was fixed.
closes https://github.com/Codeinwp/themeisle/issues/1445
=> Fix for the Build checks on the dependabot PR

inc/admin.php, tests/test-media.php
This adds support to allow SVG uploads in WordPress.
Closes #13.
1. You can try to upload SVG file to a fresh WP with and without Optimole and see if it works or not.
2. With Optimole, it should allow SVG uploads, without it won'.t.
=> Add SVG support

.distignore
Quick investigation and the issue is for some reason the distignore contained `build` folder. Removing it keeps the SDK build files.
Closes #517 .
1. Run `npm run dist` and you will notice themeisle-sdk containing its build files.
=> Fix SDK build files being ignored

inc/filters.php
When checking the page exclusions we can also check the `HTTP_REFERER` to exclude images from ajax calls within a excluded page. 
I also added an early exit condition to avoid redundant checks to run for users that do not have any exclusions added. 
Closes #437 .
1. Install the pr plugin and add an exclusion for page urls that contain `checkout` https://vertis.d.pr/i/7MG5cx.
2. Install https://wordpress.org/plugins/fluid-checkout/ and configure a small woocomerce shop (with images for products) and the fluid checkout plugin. I recommend neve + template cloud to setup a fast shop (just a suggestion).
3. From a browser where you are not logged in as admin, add a product to the cart and go to checkout, the product image should not be optimized https://vertis.d.pr/i/yhhI4s .
=> chore: checking http_referer on page exclusions #437

inc/compatibilities/divi_builder.php
The issue here was that we were applying background lazyload to the divi blog container which was breaking it.  Changed the filtering to use a regex `:not([class*="et_pb_blog"])` so we would avoid this on future class name changes. 
Closes #527 .
1. Install divi theme and create at least 10 posts(to make the navigation appear) and a use the divi blog module on a page. For this step there are more detailed steps here: https://github.com/Codeinwp/optimole-wp/issues/527 and also a useful screencast: https://vertis.d.pr/v/61xSIG .
2. Use the pr plugin and enable the backgroud lazyload option. 
3. Check that navigating between `older entries` and `newer entries` works as expected. (before the fix there will be pages with blank body)
=> chore: fixed bg lazyload breaking divi blog module #527

assets/vue/components/last-images.vue, assets/vue/store/actions.js
When you connect to Optimole and the image section is loaded, it updates dashboard stats to reflect latest count. Turned out easier than I expected without any expected issues.
Closes #508.
1. On a new instance, have some images and connect to Optimole.
2. Once the connecting finishes and "Last optimized images" section loads, you should see Image Optimized count update.
=> Update stats when last image section has loaded

cypress/e2e/test_otter_background_lazyload.js, inc/compatibilities/otter_blocks.php, inc/manager.php
Add lazyload selectors for Otter & also replace internal URLs in CSS with Optimole ones.
@GrigoreMihai I wanted to add e2e tests here. Can you give me access to the testing.optimole.com website?
Closes [#755](https://github.com/Codeinwp/optimole-service/issues/755).
1. Insert Flip and Section block from Otter
2. Add a background image to both of them.
3. The background should lazyload in frontend. Ie it should have `optml-bg-lazyloaded` class after coming into view.
=> Add Otter lazy-load selectors

assets/vue/components/compression.vue
Previously if you just toggle off the Auto Quality control, the View Sample wasn't appearing, you had to adjust the slider for it to appear. 
Closes #515.
1. Go to Media > Optimole
2. Open Settings > Advanced > Compression
3. Disable the Auto Quality toggle, and View Sample button should appear, and it should close too if you toggle it off.
=> Fix Show Sample button not displaying when expected

assets/vue/components/resize.vue, inc/admin.php, inc/app_replacer.php, inc/main.php, inc/settings.php, inc/url_replacer.php, tests/test-replacer.php
- Adds a new option to limit max-width and max-height of the served images;
- This option will be enabled by default for new users;
- This will limit the image sizes served on the frontend in the following way:
- The scale ratio is established by applying the smallest ratio between maxWidth / initialWidth and maxHeight / initialHeight;
- Then, the image initial w/h is multiplied by this ratio, obtaining the new size for generating the URL w:/h: parameters;
- Images that were served with `w`/`h` auto will be automatically be served with the **w:maxWidth** and **h:maxHeight**
Closes #506.
1. This should be tested using a staging API key. The version of the JS library that supports this should already be available (https://github.com/Codeinwp/optimole_js_lib/pull/123); 
2. Make sure that the …
=> feat: implement maxWidth and maxHeight setting

inc/compatibilities/elementor_builder.php
Adds the hook to optimize files to the different flow of css saving that elementor is using, by hooking `elementor/frontend/after_enqueue_styles` .
This will only work on elementor versions newer then october 2022 as this is when the filters were added : https://github.com/elementor/elementor/commit/61622de962a9600641bd5ac557517d7ad880282f . I think this is ok as this was added almost one year ago in elementor. 
Closes #542.
1. Install the pr plugin, neve and elementor.
2. Add some background image in a page built with elementor. 
3. Check that the background image is when viewing the page.
=> chore: add replacement hook for all elementor's css workflows #542

inc/image_properties/resize.php, tests/test-replacer.php
Changes the order in which `fp` gravity and the `el` options are added in the URL to avoid wrong formats.
Closes #544 .
1. Install the pr plugin.
2. Download this gist as a zip file and install it as a plugin https://gist.github.com/GrigoreMihai/533d47c00647ca56dd18123f4a5e89b9 . The URL's should have the expected format in the issue.
=> chore: fixed gravity and enlarge order conflict #544

assets/vue/components/filter-control.vue, tests/test-replacer.php
Adds `webp` to  the extensions exclusions.
The frontend tests are failing for elementor as I uptated the plugin on the testing website, is not related to this.
Closes #543 .
1. Install the pr plugin. 
2. Add some images with `webp` extension to the pages.
3. Go to `Adnvanced > Exclusions` and add the `webp` exclusion. 
4. Now the added webp images should be skipped from optimization.
=> chore: added webp extension exclusion #543

inc/tag_replacer.php
This will add `loading='eager'` to the first images excluded from lazyload when native lazyload is enabled. Does not add eager loading for GIF images. (added the reasoning for GIF's into the performance details). 
Also provides a filter to disable this just in case some users do not need it. It's also good for testing purposes, the gist for it is here: https://gist.github.com/GrigoreMihai/3e7a74836d7d1212966f86a43f640856 .
We not need to check the excluded count where the code was added because it is checked here: https://github.com/Codeinwp/optimole-wp/blob/master/inc/lazyload_replacer.php#L242 before the added part will be called. 
The frontend tests that are currently failing are because of the testing site elementor update. Once that issue passes qa I will sync this and make sure the …
=> chore: added loading eager for lazyload excluded images #762 

inc/admin.php, inc/conflicts/conflicting_plugins.php, tests/test-plugin-conflicts.php
This adds notices when a conflicting plugin is installed alongside Optimole WP. The notices are dismissable and we also record for which plugin they have been dismissed, in case you install a new plugin that also poses a conflict.
This should help showcase the feature: https://www.loom.com/share/6b070c8d0d524145a7b9a1b6633d409d
Closes https://github.com/Codeinwp/optimole-service/issues/761.
1. Install few of the conflicting plugins, the list is here: https://github.com/Codeinwp/optimole-wp/blob/a82c214ab1d574a4c4627f2cf0a1af23c4d9d265/inc/conflicts/conflicting_plugins.php#L45-L52
2. You should see a Dashboard notice that should be dismissable.
3. After dismissing the notice, if you install any new conflicting plugin, the notice should appear again but this time only with the conflicting …
=> Add plugin conflict notice

inc/compatibilities/elementor_builder.php
Checks that the plugin is connected to the service before running Elementor compatibilities. The warning should not happen anymore.
Closes #572.
1. Use PHP 7.4 (I replicated it with PHP 7.4.33); 
2. Have Elementor installed and create a page using it, containing an image;
3. Install and activate Optimole but don't connect it;
2. Go to the Elementor page created initially, and there should be no warning;
3. Elementor compatibilities should still work fine when the plugin is connected;
=> fix: compatibilities loaded even when service is disconnected 

inc/compatibilities/compatibility.php, inc/compatibilities/elementor_builder.php, inc/compatibilities/smart_search_woocommerce.php, inc/compatibilities/yith_quick_view.php, inc/manager.php
The abstract compatibility class checks the service connection before evaluating other conditions in classes that inherit it.
Closes #579.
Unfortunately, we can't test with the plugin mentioned in the issue unless we have the pro version somewhere. One way to test this would be to see if compatibility with other plugins still loads.
We can check if the Elementor compatibility works fine. Similar testing to what we have in this PR should be acceptable because this removes the code that fixes that and solves it in a more abstract way: https://github.com/Codeinwp/optimole-wp/pull/574
=> fix: ensure service is connected before loading compatibilities

assets/src/parts/connected/Sidebar.js, inc/admin.php
This adds a support button to the Sidebar if you view the plugin dashboard as a premium user and autofills the contact form on the website. 
Closes [#754](https://github.com/Codeinwp/optimole-service/issues/754).
1. Connect to Optimole using a non-free account.
2. You should see a support button in the Optimole dashboard sidebar.
3. Clicking on it should load the contact page on the Optimole website with the details pre-filled.
=> Add support link for Premium users

inc/admin.php, inc/lazyload_replacer.php, tests/test-lazyload.php
Removes adding `data-opt-src` placeholder when native lazyload is enabled. 
Removes the redundant fallback script: https://vertis.d.pr/i/VCDGzP. 
When native lazyload is enabled and other lazyloads are disabled removes the lazyload script completely. 
Closes https://github.com/Codeinwp/optimole-service/issues/842 .
1. Install the pr plugin.
2. For any page and plugin setup this part of the lazyload script is removed https://vertis.d.pr/i/VCDGzP.
3. Check that when native lazyload is enabled `data-opt-src` is no longer added to image tags. 
4. Check that background lazyload still works with native lazyload enabled.
5. With native lazyload enabled, background lazyload and video lazyload disabled the js library is removed: https://vertis.d.pr/i/btGKzm .
=> chore: removed native lazyload fallback

.distignore, .github/workflows/build-dev-artifacts.yml, bin/dist.sh, composer.json, development.php, package.json
This adds a development.php file to the codebase which loads when you setup the env locally and by default loads the Optimole test constants. It has a constant than you can toggle to use those if you want.
The dev build also includes the development build of React code which should provide more descriptive errors in console.
It also adds the prod & dev build to the Github comments.
Closes #567.
1. When you install build zip from comments, it should work as normal.
2. When you install the dev build zip from comments, it should work as normal too and by default connect to staging site.
=> Add dev build and development.php file

inc/manager.php
`wp_footer` hook is executed during the Rest API requests when rendering the widget iframes in the admin, so I've added a  check that we're not in a REST API request.
**LATER EDIT:** This seems to be a known issue, but it's been two years since it was opened: https://core.trac.wordpress.org/ticket/53801
Closes #590.
1. Activate the Optimole badge;
2. It should work as before on frontend;
3. It shouldn't be visible in the widgets screen in admin;
4. It shouldn't be visible in the widgets screen in the customizer;
=> fix: Optimole banner appearing in the admin inside widget iframes

inc/hero_preloader.php, inc/manager.php, tests/test-preloading.php
This tries to detect Hero Images and adds `fetchpriority="high"` to them. It looks for the first image that matches the description and doesn't add it to any other images.
It also adds it to the first Site Logo if the theme is using WordPress' core logo function. Apart from that, for Hero Images it looks for:
- Page Header, if called using WP Core functions.
- Post Thumbnail, if called and used using WP Core functions.
- Image: If called using wp_get_attachment_image + it is the thumbnail of the post.
- Image in Post Content: If nothing is fount until the content, it uses the `wp_content_img_tag` to find the first image of the post and adds it to it. This also works with FSE themes.
I ran some tests with Neve & Neve FSE and here how the comparisons look, I'd recommend that we also try to …
=> Add Hero Image Preloader

inc/image.php, inc/url_replacer.php, tests/test-replacer.php
- Adds compatibility for the new AVIF flag in the URLs from this PR: https://github.com/Codeinwp/optimole-lambda-functions/pull/456
- Adds the `ig:avif` flag to images when the user disables the AVIF option in the plugin settings;
Closes Codeinwp/optimole-service#884.
1. Enable the plugin and add a image to a page that gets loaded as AVIF; You can check this in the inspector window under the Network tab under the Type of the resource:
3. You can also check that the URL displayed on the page does not contain the `ig:avif` flag inside it;
4.  Disable the `Enable avif conversion` option inside the plugin settings, under **Advanced > Compression**;
5. You might need to clear the cached images from the **General > Clear cached resources** section in the settings;
6. Go back to the website and …
=> feat: add avif-ignore flag

assets/src/dashboard/parts/Main.js, assets/src/dashboard/utils/api.js, assets/src/dashboard/utils/helpers.js, inc/admin.php, inc/dam.php
- Adds Optimole dashboard page and subpages;
- The following pages are added: 
- Main page -> leads to the dashboard;
- Settings -> leads to the dashboard and autofocuses the **Settings** tab;
- Cloud Library -> when cloud browsing feature is enabled;
- Adds mechanism to autofocus dashboard tabs when coming from an URL with the respective hash ( `#settings`, `#dashboard`, `#help`);
- The URL also changes when changing the tabs manually;
- When already in the dashboard, the links in the sidebar should navigate to the proper tab instead of reloading the page;
- Redirects old dashboard URL `upload.php?page=optimole` to new dashboard link: `admin.php?page=optimole`- this is done to make sure that old links in other plugins do not break.
Closes Codeinwp/optimole-service#986.
1. Check that the …
=> Add Dashboard pages

assets/src/dashboard/parts/connected/settings/Lazyload.js, inc/admin.php, inc/lazyload_replacer.php, inc/settings.php, tests/test-lazyload.php
- Adds setting for generic lazyload placeholder color; 
<details>
<summary>Screenshots</summary>
</details>
Closes #624.
1. Turn on **Enable generic lazyload placeholder** under **Settings > Lazyload**;
2. The button for the placeholder color should appear under the setting, allowing you to select a color;
3. This color will be empty by default - the placeholder being transparent;
4. Create a page containing images - you can also lower the **Exclude the first X images from lazyload** to **0** so all images on the page get lazyloaded (this is not going to work with DAM images as they are not lazyloaded yet);
5. You can enable network throttling under the browser inspector settings (Slow 3G) should be enough, so you have time to see the placeholders;
6. The placeholder for the lazyloaded …
=> feat: add option for generic lazy-loading placeholder color

inc/app_replacer.php, inc/dam.php, inc/image.php, inc/manager.php, inc/media_offload.php, inc/tag_replacer.php, inc/url_replacer.php, tests/test-dam.php, tests/test-lazyload.php, tests/test-replacer.php
- Filters out the DAM images from processing in offload and rollback;
- Allows DAM-imported images through the replacers so they can be lazyloaded, and their URLs can be replaced;
- Updates the `Optml_Image` class to add another branch for building DAM image URLs;
- When inserting an image sourced from the DAM, we now insert a `/dam:1` URL path parameter so we can efficiently identify these URLs when replacing them;
- Ensures that the height/width of DAM images can't be 0 when using an image size;
**Note for code review:** I'm a bit weary of the fix I had to do for Elementor images to pick up the proper `img` tag width and height (i.e., [forcing the core to see that there's an attached file](https://github.com/Codeinwp/optimole-wp/pull/653/files#diff-f7384a8d30d9b4d82a4194865bb6a45296dc811 …
=> DAM images lazyload and URL parameters

assets/src/dashboard/parts/connected/index.js, assets/src/dashboard/parts/connected/settings/index.js
This adds a notice if you try to leave the page after changing settings you try to leave the page without saving your changes.
Closes https://github.com/Codeinwp/optimole-service/issues/1034.
1. Update few settings and confirm:
2. You see a notice when you try reloading the page if the changes aren't saved.
3. you shouldn't see that message if changes are saved.
4. Apart from that, saving of settings should work as before.
=> feat: add leave page confirmation if settings are updated [ref: #1034]

assets/src/dashboard/parts/components/ProgressBar.js, assets/src/dashboard/parts/connected/dashboard/LastImages.js, assets/src/dashboard/parts/connected/dashboard/index.js, assets/src/dashboard/parts/connected/settings/Compression.js, assets/src/dashboard/parts/connected/settings/OffloadMedia.js, assets/src/dashboard/parts/connecting/index.js, assets/src/dashboard/style.scss, tailwind.config.js
This PR replaces the native Progress Bar usage with a new ProgressBar component that looks similar in all browsers.
It appears in 5 locations:
- Loading during the first connect
- Images loading after first connect
- Main Dashboard image usage
- In "Enable Auto Quality powered by ML(Machine Learning)" setting's View Sample
- In Offloading/Rollback loading
Closes #660.
1. Make sure the ProgressBar is the same as before and looks the same in all browsers.
=> fix: redo progress bar for consistency

inc/main.php
This PR removes scheduled cron events during the uninstall to get rid of the stray jobs.
Closes #659.
1. First, install [WP Control](https://wordpress.org/plugins/wp-crontrol/)
2. To reproduce the issue, you can connect to Optimole and then deactivate the plugin, you will find (using WP Control) couple of stray cron jobs from Optimole named `optml_daily_sync` and `optml_pull_image_data_init`
3. After applying this PR, you can reproduce the last step and the cron jobs should not be visible anymore.
=> fix: remove scheduled crons during uninstall

assets/src/dashboard/parts/connected/CSAT.js, inc/admin.php
- Removes CSAT tooltip.
Closes Codeinwp/optimole-service#1077.
Follow the steps described here to show the CSAT popup: https://github.com/Codeinwp/optimole-wp/pull/575#issue-1772970164
1. On the second page of the CSAT popup there should be no tooltip anymore, or the button that opened the tooltip;
* ~[ ] Have you written new tests for your changes, as applicable?~
=> fix: remove CSAT tooltip [closes Codeinwp/optimole-service#1077]

assets/src/dashboard/parts/Main.js, assets/src/dashboard/parts/connected/Toasts.js, assets/src/dashboard/utils/api.js, assets/src/dashboard/utils/helpers.js, inc/admin.php
- Adds toasts notifications system;
- Adds notifications for when settings are saved;
- Adds notifications for when cache is cleared;
Closes #696.
1. Change any settings and save, a toast notice should appear confirming the change happened;
2. Clear the cache - a toast should appear acknowledging that cache was cleared;
* ~[ ] Have you written new tests for your changes, as applicable?~
=> feat: add toast notifications system

assets/src/dashboard/parts/connected/settings/Compression.js
Fixes value of Progress Bar in "Enable Autoquality" option being opposite of the actual compression.
Closes #692.
1. In Dashboard, assuming you already have images compressed, visit the Settings and disable "Enable Auto Quality powered by ML(Machine Learning)"
2. Click on View Sample and confirm the value of Progress Bar is same as compression numbers.
=> fix: wrong process value in Compression Ratio

assets/src/dashboard/parts/connected/settings/Resize.js, inc/admin.php, inc/app_replacer.php, inc/settings.php, inc/url_replacer.php
- Removes the `Resize large images original source` setting;
- Enables the `Limit Image Dimensions` setting for old users;
- Changes the `Limit Image Dimensions` setting to be enabled by default in all cases; 
Closes #675.
1. Go to the Optimole Settings page (**Optimole Dashboard > Settings > Resize**) 
2. The `Resize large images original source` setting should not exist anymore;
3. For users that updated the plugin, the `Limit Image Dimensions` setting should be turned on now;
4. For new users, the `Limit Image Dimensions` setting should be turned on by default;
5. The setting should function just as before (https://github.com/Codeinwp/optimole-wp/pull/538), resizing images larger than 1920x1080 (or whatever limit is set under the `Limit Image Dimensions` setting);
6. You can check this …
=> feat: remove Resize large images original source

inc/manager.php
Compatibility layer for [Motion.page](https://motiob.page) builder
=> fix: Motion.page iFrame & builder compatibility

inc/dam.php
- Uses proper enqueue hook for media modal script (`wp_enqueue_media`);
- Adds compatibility with all media modals loaded in the admin;
Closes #618.
1. Install Beaver Builder lite and enable Cloud Library browsing;
2. Edit a page with Beaver builder - cloud images should be available and work as expected;
3. Test that Elementor and the core editor integration still works fine; 
* ~[] Have you written new tests for your changes, as applicable?~
=> fix: proper integration with media modal enqueue [closes #618]

inc/compatibilities/wpml.php, inc/traits/dam_offload_utils.php
Ensures that we check the source ID for duplicated WPML attachments, so the conditionals apply properly.
=> fix: offloading WPML compatibility

inc/manager.php
Fixes preview mode not replacing Offloaded URLs. 
Closes #801
=> fix: preview images not working with offload enabled [closes #801]

inc/media_offload.php, tests/test-media.php
fix: offloaded attachments from other sources getting replaced when post is saved even if there is no associated attachment
=> Fix: offload copy-paste between sites

inc/dam.php
I've used the elementor/image_size/get_attachment_image_html hook with the $image_size_key argument instead of $settings['image_size'] because $settings['image_size'] returns an array, which causes a fatal error.
Ref: https://tinyurl.com/2a6va6mf
I tested it with PHP 8.0 and encountered this error.
Closes #828
1. Install and activate the latest version of Elementor.
2. Install and activate the latest version of Optimole.
3. Create a new page in WordPress with Elementor.
4. Add the "Image Box" widget to the page and select the image from Optimole DAM.
5. Save the changes and attempt to view the page, you will experience some layout shifts, or unable to save the page.
6. Reload the Elementor editor screen
=> Fix compatibility issue elementor

inc/cli/cli_setting.php
Small fix to the `clear_cache` command that I found fixing an issue for a client. It says `--type` defaults to images, but that doesn't work in practice.
=> make `--type` option optional with `clear_cache` command

inc/main.php
Added the following filter to hide the SDK promo notice.
`add_filter( 'themeisle_sdk_ran_promos', '__return_false' );`
Issue https://github.com/Codeinwp/themeisle/issues/1676
=> Hide SDK random promo notice

assets/src/dashboard/parts/components/Modal.js, assets/src/dashboard/parts/connected/settings/OffloadMedia.js, assets/src/dashboard/utils/api.js, inc/media_offload.php, inc/rest.php
- Fixes an issue with the modal icon not being displayed properly;
- Adds a mechanism to run a cleanup of the error meta for previously offloaded attachments when the sync is ran manually;
Closes Codeinwp/optimole-service#1292.
* ~[ ] Have you written new tests for your changes, as applicable?~
=> Feat: force reoffload

assets/src/dashboard/parts/connected/settings/CloudLibrary.js, assets/src/dashboard/store/selectors.js
- Changes to adapt this with the sub-api keys integration from the optimole dashboard here https://github.com/Codeinwp/optimole-service/pull/1300
- If a sub-api key is used, it automatically hides the site selector option under Cloud Library
- The banner toggle will not work either, as that option is restricted on the dashboard to the root API key.
Closes Codeinwp/optimole-service#1136.
=> feat: adapt for sub-api keys [ref Codeinwp/optimole-service#1136]

inc/api.php
- Adds handling for the whitelist hard limit error;
- With the old version, nothing would happen when this error was thrown, now the user will get disconnected;
Ref Codeinwp/optimole-service#1169.
Needs this PR: https://github.com/Codeinwp/optimole-service/pull/1299
=> chore: adapt for whitelist limit error

assets/src/dashboard/parts/connected/index.js, inc/admin.php, inc/dam.php, optimole-wp.php, package-lock.json, package.json, tests/static-analysis-stubs/optimole-wp.php
- Added internal page hooks
- Remove Formbricks as a dependency 
- Loading survey via internal page hooks
Closes https://github.com/Codeinwp/themeisle/issues/1687
1. Use the latest Themeisle SDK release.
2. Go to `/wp-admin/admin.php?page=optimole&formbricksDebug=true#dashboard`
3. In the Browser Console you should see:
=> feat: load Formbricks survey via internal pages hooks

assets/src/media/modal/messageHandler.js
"I've detached event listeners to fix the image insert issue in other fields."
Closes https://github.com/Codeinwp/optimole-wp/issues/670
=> Fixed detach listeners after adding image

assets/src/dashboard/parts/connected/settings/FilterControl.js
I've reset the state data after the user adds an exclusion filter. 
Closes https://github.com/Codeinwp/optimole-wp/issues/681
1. Optimole > Settings > Exclusions
=> Reset exclusions filter values

inc/admin.php
I've removed the `$this->settings->is_connected()` check to display the conflict notice even if the user hasn't connected their account. 
Closes https://github.com/Codeinwp/optimole-service/issues/1373
1. Install competitors plugins(Smush, ShortPixel Image Optimizer, Imagify) and activate
=> Fixed always show conflict notice

inc/tag_replacer.php
Added a condition to skip image downsizing for REST API requests.
```
if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
return $image;
}
```
Closes https://github.com/Codeinwp/optimole-wp/issues/704
=> Fixed image downsize issue when lazyload disabled

assets/src/dashboard/parts/components/RadioBoxes.js, assets/src/dashboard/parts/connected/settings/Menu.js
- Moved `Image Storage` menu before the `Advanced Settings` menu.  
- Fixed broken text issue on Safari.
Closes https://github.com/Codeinwp/optimole-service/issues/1340
=> feat: move image storage menu

inc/admin.php
Make the field title clearer. 
Closes https://github.com/Codeinwp/optimole-service/issues/1408
Optimole > settings > Advanced -> Exclusions
=> feat: Clarify the exclusion field title

assets/src/dashboard/parts/connected/Sidebar.js, assets/src/dashboard/parts/connected/index.js
- Lowers sidebar width in plugin admin to a width of 350px when in horizontal layout. 
Closes Codeinwp/optimole-service#1337.
1. Install the plugin;
2. Check if the sidebar width is 350px;
=> feat: rework sidebar width in plugin admin [closes Codeinwp/optimole-service#1337]

assets/src/dashboard/parts/connecting/index.js
- Lowers the waiting time for connection to 5 seconds instead of 25.
Closes Codeinwp/optimole-service#1349.
1. Either connect with an existing api key or creating a new account;
2. The loading should take a lot less than previously, while the onboarding images should be sent to the service for optimization;
=> fix: reduce loading time for plugin connection

assets/src/dashboard/parts/connected/OptimizationStatus.js
Marked image scaling feature as disabled when lazy load is inactive.
Closes https://github.com/Codeinwp/optimole-service/issues/1347#issuecomment-2751702745
=> fix: disable image scaling when lazyload is off

inc/media_offload.php, inc/v2/Offload/ImageEditor.php, inc/v2/Offload/Loader.php
Add Image editor to be used when editing images that are offloaded on Optimole. 
For now this is just preventing the editing of those images which caused to break images on edit using the core editors. 
https://github.com/Codeinwp/optimole-wp/issues/778
=> Add Image editor to prevent errors with offloaded images

assets/src/dashboard/parts/connected/settings/General.js
- Hides the badge setting for inactive users.
Closes Codeinwp/optimole-service#1438 .
1. Deactivate the user on the dashboard;
2. Refresh the stats and check that the badge setting is hidden;
=> feat: hide bagde toggle if the user is inactive [ref Codeinwp/optimole-service#1438]

assets/src/dashboard/parts/components/Tooltip.js, assets/src/dashboard/parts/connected/OptimizationStatus.js, assets/src/dashboard/parts/connected/SPCRecommendation.js, assets/src/dashboard/parts/connected/Sidebar.js, assets/src/dashboard/parts/connected/index.js, assets/src/dashboard/parts/connected/settings/Menu.js, assets/src/dashboard/utils/icons.js, inc/admin.php
- Disables other settings tabs when image handling is turned off;
- Cards on the main dashboard page should link to the general tab if image handling is turned off;
- Makes the statuses of the `Optimization Status` card update live based on current settings (no need to save now);
- Fixes consistency in styling and layout for the sidebar cards;
- Makes the connection details card more compact;
Closes Codeinwp/optimole-service#1386.
1. Disable image handling in the general tab, this will also disable other tabs than `General`;
2. Cards on the main dashboard page pointing to `Enable Offload Images`& `Advanced Settings` should just switch to `General` tab;
3. The `Optimization Status` card should react to setting changes instantly;
=> feat: disable other settings tabs when image handling is disabled & improve UI

assets/src/dashboard/parts/connected/settings/Compression.js, assets/src/dashboard/style.scss, inc/admin.php, inc/settings.php
- Added a new toggle group control for selecting compression modes: Speed Optimized, Quality Optimized, and Custom.
- Updated the Compression component to handle the new compression mode logic and state management.
- Enhanced the admin settings to include compression mode options and their descriptions.
- Updated styles for the toggle group control to improve UI consistency.
Adds a compression preset which control individual settings for compression. 
https://github.com/Codeinwp/optimole-service/issues/1435#issuecomment-2775527936
1. Go to Settings -> Compression
2. Change the compression preset
If you previously had custom mode and you switch to sped/optimized and you switch back to custom, the previously values should show up, unless you save the mode.
=> Implement compression mode settings in the dashboard

assets/js/media.js, assets/src/dashboard/parts/connected/index.js, assets/src/dashboard/parts/connected/settings/Compression.js, assets/src/dashboard/parts/connected/settings/OffloadMedia.js, assets/src/dashboard/style.scss, assets/src/dashboard/utils/api.js, inc/admin.php, inc/media_offload.php, inc/rest.php, inc/settings.php, inc/v2/Offload/ImageEditor.php, inc/v2/Offload/Loader.php
Removed bulk actions support and implement inline offload/rollback of images for better experience. 
- Replaced `get_image_count` with `move_images` in the media offload process for better clarity.
- Updated the rollback process to use `move_images` instead of `get_image_count`.
- Introduced a new REST API endpoint for moving images, allowing for offloading and rollback actions.
- Enhanced the admin interface by adding scripts and styles for the media management screen.
- Improved action handling for image processing, ensuring better performance and user experience.
https://github.com/Codeinwp/optimole-wp/issues/834
=> Refactor media offload functionality and enhance REST API integration

inc/media_rename/attachment_edit.php
- Checks that `get_current_screen` function is loaded before hooking into the attachment fields for the rename / replace fields;
=> fix: fatal error thrown because get_current_screen function is not loaded

inc/compatibilities/jetpack.php, inc/manager.php
When JetPack performs the synchronization, it pulls the WP_Posts without Optimole applied. The compatibility modifies the contents of the payload so that the content and the featured image include Optimole optimizations.
```css
background-image: url(&quot;https://i0.wp.com/mlhgoovhyl5g.i.optimole.com/w:auto/h:auto/q:mauto/ig:avif/https://robert-optimole-test.instawp.co/wp-content/uploads/2025/09/167113836-efdbde32-7863-4a24-9d2d-979025b51260.jpeg?quality=80&ssl=1&strip=info&w=1200&quot;); background-size: cover; background-repeat: no-repeat; background-position: center center;
```
When received by Google, they switch our CDN with theirs, but the origin is Optimole.
```css
src="https://ci3.googleusercontent.com/meips/ADKq_NZC7WDiAynJxsi287Z8tYysdNP_dn6X2MyCrQstkwS67N_tzKyN5o-EUKYzujjqfjJCTH …
```
=> fix: add compatibility with JetPack

assets/src/dashboard/parts/connected/dashboard/index.js, inc/admin.php
Added clarity for ‘visits’ metric with helper text and renewal info
Closes https://github.com/Codeinwp/optimole-service/issues/1544
=> feat: helper text for 'visits' metric

assets/js/modal-attachment.js, inc/media_rename/attachment_edit.php
- Added a filter for actions on the media tab to add a redirect to the Rename or Replace edit screen
- Extended the attachment modal to add a redirect to the Rename or Replace edit screen
Closes https://github.com/Codeinwp/optimole-service/issues/1569
=> feat: increase the visibility of rename/replace

assets/src/dashboard/parts/connected/settings/Compression.js, inc/settings.php
- Enabled `network_optimization` as the default for new users to match the Speed Optimization profile.
Closes https://github.com/Codeinwp/optimole-service/issues/1560
https://github.com/user-attachments/assets/d5f71110-c6ec-4f4d-a2ad-b62ae04e567b
1. Use a new account on a new instance
2. Check if the Network Optimization is enabled when going to Custom
> [!WARNING]
> AVIF will be hidden in https://github.com/Codeinwp/optimole-wp/pull/975 so we can ignored in this PR
=> fix: preset settings

assets/src/dashboard/parts/connected/OptimizationStatus.js, assets/src/dashboard/parts/connected/Sidebar.js, assets/src/dashboard/parts/connected/index.js, inc/admin.php
The user can now interact with the optimization status dashboard using:
- Image Handling: Redirects to the settings page/enables the setting.
- Smart Lazy-Loading, Image Scaling: Programmatically disable/enable from status.
Closes https://github.com/Codeinwp/optimole-service/issues/1490
- If image handling is disabled, Lazy & Scaling are also disabled, along with the hidden button.
- Scaling depends on Lazy; if Scaling is enabled but you disable Lazy, Scaling will also be disabled.
- If Lazy is disabled, when enabling, it will not modify the Scaling.
https://github.com/user-attachments/assets/8eae435c-125e-4016-826e-8cd4c34d376c
=> refactor: dashboard optimization status

assets/src/dashboard/parts/components/Modal.js, assets/src/dashboard/parts/connected/settings/OffloadMedia.js, assets/src/dashboard/store/reducer.js, assets/src/dashboard/store/selectors.js, inc/admin.php, inc/main.php
> [!IMPORTANT]
> The server changes are available on https://github.com/Codeinwp/optimole-service/pull/1584
Closes https://github.com/Codeinwp/optimole-service/issues/1543
> [!IMPORTANT]
> All the backend changes are on https://staging-dashboard.optimole.com/, use this ZIP to connect to it 
[optimole-test (1).zip](https://github.com/user-attachments/files/22655304/optimole-test.1.zip) to test this PR
1. If you have a Free account (older or new) without Offloading, you should not be able to activate offloading with the build from this PR (you will see a notice to upgrade your plan)
2. If you have a Free account with Offloading active and you install the build from this PR, you will see a notice about the plan changes. (So activate Offloading first with an older version before checking).
=> feat: add offload restrictions
